---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  containers:
  - image: choejsager/asp-frontend:v1
    name: frontend
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 100m
        memory: 200M
      requests:
        cpu: 10m
        memory: 50M
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: backend
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: backend
  name: backend
spec:
  containers:
  - image: choejsager/asp-backend:v1
    name: backend
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 100m
        memory: 200M
      requests:
        cpu: 10m
        memory: 50M